export enum ActionTypes {
  SET_STATUS = 'SET_STATUS',
  SET_RACES = 'SET_RACES',
  SET_RACE = 'SET_RACE',
  SET_ACTIVE_PARTICIPANTS = 'SET_ACTIVE_PARTICIPANTS',
  SET_BET_VALUE = 'SET_BET_VALUE',
  SET_BETS = 'SET_BETS',
  CLEAR_RACE_DATA = 'CLEAR_RACE_DATA',
  CLEAR_BETS_DATA = 'CLEAR_BETS_DATA',
  FETCH_START = 'FETCH_START',
  FETCH_SUCCESS = 'FETCH_SUCCESS',
  FETCH_FAILURE = 'FETCH_FAILURE'
}
