export enum Actions {
  SET_STATUS = 'SET_STATUS',
  SET_RACES = 'SET_RACES',
  SET_FILTRED_RACES = 'SET_FILTRED_RACES',
  SET_RACE = 'SET_RACE',
  SET_PARTICIPANTS = 'SET_PARTICIPANTS',
  SET_ACTIVE_PARTICIPANTS = 'SET_ACTIVE_PARTICIPANTS',
  SET_BET_VALUE = 'SET_BET_VALUE',
  SET_BET = 'SET_BET'
}
